### ISSUE TITLE
Latest MagicMirror version 2.16 breaks this module

### ISSUE THREAD

**Issue by spospordo** [vincep5/MMM-Pollen#5]
With MagicMirror Version v2.16.0 the dependency request was removed. request is deprecated and should not be used anymore (see npm request). This should be no problem for modules using request but some modules didn’t setup request in there own package.json, they did rely on that this dependency comes with MagicMirror.

So if your container doesn’t start with MagicMirror v2.16.0 or later and you find something like Error: Cannot find module 'request' you should open an issue in the module project to get this fixed.

https://khassel.gitlab.io/magicmirror/faq/#error-cannot-find-module-request

**Comment by TheHoboArk** [comment]
For those trying to get this working (because it breaks the mirror to enable this module, see below. Once the author fixes it, this should no longer be necessary.

To get your MagicMirror running you can use the following workaround:
---
if your container doesn’t start see the section above
login into the container with `docker exec -it mm bash` and navigate into the folder of the module, e.g. `cd modules/MMM-Pollen`
check with 

`ls -la`

 if the folder contains a file package.json, if not run 

`npm init -y`

run 

`npm install request`

---

**Comment by TheHoboArk** [comment]
As of today, Author has updated the npm dependencies, so **_IF, AND ONLY IF, you ran the above "temporary solution"_** I provided, then you will need to run `rm package-lock.json` and `rm package.json` in the MMM-Pollen directory.

Once those 2 files are removed, will need to run `git pull` then `npm install` in that same folder.

Once all of that is completed, will need to go back to `cd ~/magicmirror/run` then `docker-compose up -d --force-recreate` to "restart" the MagicMirror, then it should all work.

**Comment by vincep5** [comment]
Yes, thank you for the write up on it @TheHoboArk
